MockingBird/Controllers/AdGroupLookupController.cs
using MockingBird.Models;
using System;
using System.Collections.Generic;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MockingBird.Controllers
{
    public class AdGroupLookupController : Controller
    {
        // GET: AdGroupLookup
        public ActionResult Index(string UserName)
        {
            ViewBag.AdGroupLookup = null;
            AdGroupLookup lookupResults = new AdGroupLookup();

            PrincipalContext domain = new PrincipalContext(ContextType.Domain);
            List<string> domainGroups = new List<string>();

            try
            {
                if (UserName != null)
                {
                    UserPrincipal user = UserPrincipal.FindByIdentity(domain, UserName);
                    PrincipalSearchResult<Principal> groups = user.GetAuthorizationGroups();
                    lookupResults.Name = user.Name;

                    foreach (Principal p in groups)
                    {
                        if (p is GroupPrincipal)
                        {
                            domainGroups.Add(p.ToString());
                        }
                    }
                }

                lookupResults.UserName = UserName;
                lookupResults.AdGroupName = domainGroups.OrderBy(o => o).ToList();

                ViewBag.AdGroupLookup = lookupResults;
            }
            catch
            {
                lookupResults.UserName = "Username does not exists";
                ViewBag.AdGroupLookup = lookupResults;
            }

            return View();
        }

        // GET: AdGroupLookup/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdGroupLookup/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdGroupLookup/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdGroupLookup/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdGroupLookup/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdGroupLookup/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdGroupLookup/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MockingBird/Controllers/DiskCheckersController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MockingBird.Models;
using PagedList;

namespace MockingBird.Controllers
{
    public class DiskCheckersController : Controller
    {
        public DriveSpaceDBContext db = new DriveSpaceDBContext();
        private ServerDBContext sdb = new ServerDBContext();

        // GET: DiskCheckers

        public ActionResult Index(string searchString, int? page)
        {
            var DiskCheckList = from s in db.DiskCheckers select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                DiskCheckList = DiskCheckList.Where(s => s.ServerName.Contains(searchString));
                page = 1;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(DiskCheckList.OrderBy(s => s.ServerName).ToPagedList(pageNumber, pageSize));
        }

        // GET: DiskCheckers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiskChecker diskChecker = db.DiskCheckers.Find(id);
            if (diskChecker == null)
            {
                return HttpNotFound();
            }
            return View(diskChecker);
        }

        // GET: DiskCheckers/Create
        public ActionResult Create()
        {
            var Integer100List = new List<int>();
            for (var i = 1; i < 101; i++)
            {
                Integer100List.Add(i);
            }

            var EmailAlertMinuteList = new List<int>();
            EmailAlertMinuteList.Add(1);
            EmailAlertMinuteList.Add(5);
            EmailAlertMinuteList.Add(10);
            EmailAlertMinuteList.Add(15);
            EmailAlertMinuteList.Add(30);
            EmailAlertMinuteList.Add(60);
            EmailAlertMinuteList.Add(90);
            EmailAlertMinuteList.Add(120);
            EmailAlertMinuteList.Add(180);
            EmailAlertMinuteList.Add(360);
            EmailAlertMinuteList.Add(720);
            EmailAlertMinuteList.Add(1080);
            EmailAlertMinuteList.Add(1440);

            ViewBag.Integer100List = new SelectList(Integer100List, "LowDiskPercentage");
            ViewBag.EmailAlertMinuteList = new SelectList(EmailAlertMinuteList, "PollTime");
            ViewBag.ServerList = new SelectList(sdb.Servers.OrderBy(x => x.ServerName), "ServerName", "ServerName");

            return View();
        }

        // POST: DiskCheckers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ServerName,DriveLetter,LowDiskPercentage,PollTime,AdminEmailAlert,AlertSubscribers,SubcriptionEmailAddresses,Disable,ShowOnDash,LastRan,DriveSize,AvailableSpace,IgnorePollTimeOnNextRun")] DiskChecker diskChecker)
        {
            if (ModelState.IsValid)
            {
                db.DiskCheckers.Add(diskChecker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(diskChecker);
        }

        // GET: DiskCheckers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiskChecker diskChecker = db.DiskCheckers.Find(id);
            if (diskChecker == null)
            {
                return HttpNotFound();
            }
            return View(diskChecker);
        }

        // POST: DiskCheckers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ServerName,DriveLetter,LowDiskPercentage,PollTime,AdminEmailAlert,AlertSubscribers,SubcriptionEmailAddresses,Disable,ShowOnDash,LastRan,DriveSize,AvailableSpace,IgnorePollTimeOnNextRun")] DiskChecker diskChecker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(diskChecker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(diskChecker);
        }

        // GET: DiskCheckers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiskChecker diskChecker = db.DiskCheckers.Find(id);
            if (diskChecker == null)
            {
                return HttpNotFound();
            }
            return View(diskChecker);
        }

        // POST: DiskCheckers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DiskChecker diskChecker = db.DiskCheckers.Find(id);
            db.DiskCheckers.Remove(diskChecker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MockingBird/Controllers/HostedServersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MockingBird.Models;

namespace MockingBird.Controllers
{
    public class HostedServersController : Controller
    {
        private ServerDBContext sdb = new ServerDBContext();
        private EnvironmentDBContext edb = new EnvironmentDBContext();

        // GET: HostedServers
        public ActionResult Index()
        {
            return View(sdb.Servers.OrderBy(o => o.ServerName).ToList());
        }

        // GET: HostedServers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostedServers hostedServers = sdb.Servers.Find(id);
            if (hostedServers == null)
            {
                return HttpNotFound();
            }
            return View(hostedServers);
        }

        // GET: HostedServers/Create
        public ActionResult Create()
        {
            ViewBag.EnvironmentList = new SelectList(edb.Environments.OrderBy(x => x.EnvironmentName), "EnvironmentName", "EnvironmentName");

            return View();
        }

        // POST: HostedServers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ServerName,Environment,Comments")] HostedServers hostedServers)
        {
            if (ModelState.IsValid)
            {
                sdb.Servers.Add(hostedServers);
                sdb.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hostedServers);
        }

        // GET: HostedServers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostedServers hostedServers = sdb.Servers.Find(id);
            if (hostedServers == null)
            {
                return HttpNotFound();
            }
            return View(hostedServers);
        }

        // POST: HostedServers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ServerName,Environment,Comments")] HostedServers hostedServers)
        {
            if (ModelState.IsValid)
            {
                sdb.Entry(hostedServers).State = EntityState.Modified;
                sdb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hostedServers);
        }

        // GET: HostedServers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostedServers hostedServers = sdb.Servers.Find(id);
            if (hostedServers == null)
            {
                return HttpNotFound();
            }
            return View(hostedServers);
        }

        // POST: HostedServers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HostedServers hostedServers = sdb.Servers.Find(id);
            sdb.Servers.Remove(hostedServers);
            sdb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                sdb.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MockingBird/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="Shortcut Icon" href="favicon.ico" type="image/x-icon" />
    <title>@ViewBag.Title - Mockingbird</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head> 
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <a href="#" class="navbar-left"><img src="/Images/MockingbirdLogo.png"></a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Dashboard", "Dashboard")</li>
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Remote Monitoring
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Disk Space", "", "")</li>
                            <li>@Html.ActionLink("Reboot/Shutdown Server", "", "")</li>
                            <li>@Html.ActionLink("Remote Performance", "", "")</li>
                            <li>@Html.ActionLink("Scheduled Tasks", "Index", "RemoteScheduleTask")</li>
                            <li>@Html.ActionLink("Services", "Index", "RemoteServices")</li>
                            <li>@Html.ActionLink("Process Killer", "", "")</li>
                            <li>@Html.ActionLink("User Ad Group Checker", "Index", "AdGroupLookup")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Reporting
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Morning Checks", "", "")</li>
                            <li>@Html.ActionLink("Afternoon Checks", "", "")</li>
                            <li>@Html.ActionLink("Server Healthcheck", "", "")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Administaration
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Api Monitor", "", "")</li>
                            <li>@Html.ActionLink("Automation Monitoring", "", "")</li>
                            <li>@Html.ActionLink("Directory Counting", "", "")</li>
                            <li>@Html.ActionLink("Disk Space Monitor", "Index", "DiskCheckers")</li>
                            <li>@Html.ActionLink("Log File Monitor", "", "")</li>
                            <li>@Html.ActionLink("Mail Manager", "", "")</li>
                            <li>@Html.ActionLink("Scheduled Task Monitor", "Index", "SchedulledTasks")</li>
                            <li>@Html.ActionLink("Service Monitor", "", "")</li>
                            <li>@Html.ActionLink("Version Controller", "", "")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Configuration
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Applications", "", "")</li>
                            <li>@Html.ActionLink("Environments", "Index", "HostedEnvironments")</li>
                            <li>@Html.ActionLink("Servers", "Index", "HostedServers")</li>
                            <li>@Html.ActionLink("Schedulled Task Statuses", "Index", "SchedulledTaskStatuses")</li>
                            <li>@Html.ActionLink("Users", "", "")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mockingbird</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>