MockingBird/Models/RemoteServices.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MockingBird.Models
{
    public class RemoteServices
    {
        [Key]
        public int ID { get; set; }

        [Display(Name = "Display Name")]
        public string DisplayName { get; set; }

        [Display(Name = "Service Name")]
        public string ServiceName { get; set; }

        [Display(Name = "Startup Type")]
        public string StartupType { get; set; }

        [Display(Name = "Service Type")]
        public string ServiceType { get; set; }
        
        [Display(Name = "Status")]
        public string Status { get; set; }
    }
}

MockingBird/Controllers/RemoteServicesController.cs
using MockingBird.Enums;
using MockingBird.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.ServiceProcess;
using System.Web;
using System.Web.Mvc;

namespace MockingBird.Controllers
{
    public class RemoteServicesController : Controller
    {
        private ServerDBContext sdb = new ServerDBContext();

        // GET: RemoteServices
        public ActionResult Index(string ServerName, string ServiceName, string Start, string Stop, string Restart)
        {
            List<string> Services = new List<string>();

            //SET Service
            if (Start != null | Stop != null | Restart != null)
            {
                ViewBag.Message = null;

                using (WindowsIdentity.GetCurrent().Impersonate())
                {
                    ServiceController ServiceControl = new ServiceController(ServiceName, ServerName);

                    if (!string.IsNullOrEmpty(Start) & ServiceControl.Status != ServiceControllerStatus.Running)
                    {
                        ServiceControl.Start();
                        ServiceControl.WaitForStatus(ServiceControllerStatus.Running);
                        ViewBag.Message = ServiceStatuses.Service_Is_Now_Running.ToString().Replace("_", " ");
                    }
                    else
                    {
                        ViewBag.Message = ServiceStatuses.Service_Has_Already_Started.ToString().Replace("_", " ");
                    }

                    if (!string.IsNullOrEmpty(Stop) & ServiceControl.Status != ServiceControllerStatus.Stopped)
                    {
                        ServiceControl.Stop();
                        ServiceControl.WaitForStatus(ServiceControllerStatus.Stopped);
                        ViewBag.Message = ServiceStatuses.Service_Has_Been_Stopped.ToString().Replace("_", " ");
                    }
                    else if (!string.IsNullOrEmpty(Stop))
                    {
                        ViewBag.Message = ServiceStatuses.Service_Is_Already_Stopped.ToString().Replace("_", " ");
                    }

                    if (!string.IsNullOrEmpty(Restart))
                    {
                        try
                        {
                            ServiceControl.Stop();
                            ServiceControl.WaitForStatus(ServiceControllerStatus.Stopped);
                            ServiceControl.Start();
                        }
                        catch
                        {
                            ServiceControl.Start();
                        }
                        finally
                        {
                            ServiceControl.WaitForStatus(ServiceControllerStatus.Running);
                            ViewBag.Message = ServiceStatuses.Service_Has_Been_Restarted.ToString().Replace("_", " ");
                        }
                    }
                }
            }

            ViewBag.SelectedServerName = ServerName;
            ViewBag.ServiceDetails = null;

            if (!string.IsNullOrEmpty(ServerName))
            {
                ServiceController[] services = ServiceController.GetServices(ServerName);
                foreach (ServiceController service in services)
                {
                    Services.Add(service.DisplayName);
                }
                Services.Sort();
            }

            if (!string.IsNullOrEmpty(ServiceName))
            {
                ServiceController sc = new ServiceController(ServiceName, ServerName);
                RemoteServices ServiceDetails = new RemoteServices();

                ServiceDetails.DisplayName = sc.DisplayName;
                ServiceDetails.ServiceName = sc.ServiceName;
                ServiceDetails.ServiceType = sc.ServiceType.ToString();
                ServiceDetails.StartupType = sc.StartType.ToString();
                ServiceDetails.Status = sc.Status.ToString();

                ViewBag.ServiceDetails = ServiceDetails;
            }
            ViewBag.ServerList = new SelectList(sdb.Servers.OrderBy(x => x.ServerName), "ServerName", "ServerName");
            ViewBag.Services = Services;

            return View();
        }

        // GET: RemoteServices/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RemoteServices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RemoteServices/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RemoteServices/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RemoteServices/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RemoteServices/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RemoteServices/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MockingBird/Views/RemoteServices/Index.cshtml
@{
    ViewBag.Title = "Remote Services";
}

<h2>Remote Services</h2>

@using (Html.BeginForm())
{
    <p>
        @if (ViewBag.Services.Count == 0)
        {
            @Html.Raw("Select your server")
            @Html.DropDownList("ServerName", (SelectList)ViewBag.ServerList, "Please Select...", new { @class = "form-control" })

        <p>
            <input type="submit" value="Get Tasks" class="btn btn-default" />
        </p>
    }
    else
    {
        <p>
            @Html.Raw("Selected Server: " + "<b>" + ViewBag.SelectedServerName + "</b>")
        </p>
        <p>
            @Html.ActionLink("Change selected server", "Index", "RemoteServices")
        </p>

        @Html.Raw("Select a Service")

        <input type="hidden" value="@ViewBag.SelectedServerName" name="ServerName" />
        @*@Html.TextBox("ServerName", (string)ViewBag.SelectedServerName, new { @class = "hidden" })*@
        @Html.DropDownList("ServiceName", new SelectList(((List<string>)ViewBag.Services).Select(d => new SelectListItem { Text = d, Value = d }), "Value", "Text", "Please Select..."), new { @class = "form-control" })
        <br />
        <p>
            <input type="submit" value="Get Details" class="btn btn-default" />
        </p>
    }
        </p>

    }

@if (ViewBag.ServiceDetails != null)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Service Task Detail</th>
                <th>Value/Result</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Service Display Name</td>
                <td>@ViewBag.ServiceDetails.DisplayName</td>
            </tr>
            <tr>
                <td>Service Name</td>
                <td>@ViewBag.ServiceDetails.ServiceName</td>
            </tr>
            <tr>
                <td>Service Type</td>
                <td>@ViewBag.ServiceDetails.ServiceType</td>
            </tr>
            <tr>
                <td>Startup Type</td>
                <td>@ViewBag.ServiceDetails.StartupType</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>@ViewBag.ServiceDetails.Status</td>
            </tr>
        </tbody>
    </table>

    using (Html.BeginForm())
    {

        <p>
            <input type="hidden" value="@ViewBag.SelectedServerName" name="ServerName" />
            <input type="hidden" value="@ViewBag.ServiceDetails.DisplayName" name="ServiceName" />

            <input type="submit" name="Start" value="Start" class="btn btn-default" />
            <input type="submit" name="Stop" value="Stop" class="btn btn-default" />
            <input type="submit" name="Restart" value="Restart" class="btn btn-default" />
        </p>
    }
}

@if (ViewBag.Message != null)
{
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script type="text/javascript">
            $(document).ready(function(){
            alert('@ViewBag.Message');
            });
    </script>
}