MockingBird/Models/RemoteScheduleTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MockingBird.Models
{
    public class RemoteScheduleTask
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [Display(Name = "Scheduled Task Name")]
        public string SchedulledTaskName { get; set; }
        [Display(Name = "Status")]
        public string Status { get; set; }
        [Display(Name = "Last Task Result")]
        public string LastTaskResult { get; set; }
        [Display(Name = "Last Run Time")]
        public string LastRunTime { get; set; }
        [Display(Name = "Next Run Time")]
        public string NextRunTime { get; set; }
        [Display(Name = "Credentials")]
        public string Credentials { get; set; }
        [Display(Name = "Author")]
        public string Author { get; set; }
        [Display(Name = "Disable Action")]
        public bool Disable { get; set; }
    }
}

MockingBird/Controllers/RemoteScheduleTaskController.cs
using Microsoft.Win32.TaskScheduler;
using MockingBird.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;

namespace MockingBird.Controllers
{
    public class RemoteScheduleTaskController : Controller
    {
        private ServerDBContext sdb = new ServerDBContext();
        private SchedulledTaskStatusesDBContext tdb = new SchedulledTaskStatusesDBContext();

        // GET: RemoteScheduleTasks
        public ActionResult Index(string ServerName, string ScheduleTask, string TaskToDo)
        {
            List<string> ListOfErrors = new List<string>();
            ViewBag.ErrorList = null;
            ViewBag.SelectedServerName = ServerName;
            IDictionary<double, string> SchedulledTasksStatuses = new Dictionary<double, string>();
            List<string> SchedulledTasks = new List<string>();

            foreach (var TaskStatus in tdb.SchedulledTaskStatus)
            {
                SchedulledTasksStatuses.Add(new KeyValuePair<double, string>(Convert.ToDouble(TaskStatus.Status), TaskStatus.Description));
            }

            if (!string.IsNullOrEmpty(ServerName))
            {
                Task[] allTasks;

                using (TaskService tasksrvc = new TaskService(ServerName))
                {
                    allTasks = tasksrvc.FindAllTasks(new Regex(".*")); // this will list ALL tasks for ALL users

                    foreach (Task tsk in allTasks)
                    {
                        string str = tsk.Folder.ToString();
                        int pos = str.IndexOf(@"Microsoft", 0);
                        if (pos < 0)
                        {
                            SchedulledTasks.Add(tsk.Name);
                        }
                    }
                    SchedulledTasks.Sort();
                }
            }

            ViewBag.ScheduleDetails = null;

            if (!string.IsNullOrEmpty(ScheduleTask))
            {
                //GET ALL SCHEDULLED TASKS HERE AND MODEL IT
                using (TaskService tasksrvc = new TaskService(ServerName))
                {
                    Task[] allTasks;
                    allTasks = tasksrvc.FindAllTasks(new Regex(".*"));

                    foreach (Microsoft.Win32.TaskScheduler.Task tsk in allTasks)
                    {
                        if (tsk.Name == ScheduleTask)
                        {
                            RemoteScheduleTask TaskDetails = new RemoteScheduleTask();

                            TaskDetails.SchedulledTaskName = tsk.Name;
                            TaskDetails.Author = tsk.Definition.RegistrationInfo.Author;
                            TaskDetails.Credentials = tsk.Definition.Principal.UserId;
                            TaskDetails.Disable = Convert.ToBoolean(tsk.IsActive);
                            TaskDetails.LastTaskResult = tsk.LastTaskResult.ToString();
                            TaskDetails.LastRunTime = tsk.LastRunTime.ToString();
                            TaskDetails.NextRunTime = tsk.NextRunTime.ToString();
                            TaskDetails.Status = tsk.State.ToString();

                            ViewBag.ScheduleDetails = TaskDetails;

                            //START, STOP, ENABLE, DISABLED
                            Task task = tasksrvc.FindTask(tsk.Name);
                            switch (TaskToDo)
                            {
                                case "Start":
                                    try
                                    {
                                        task.Run();
                                        task.RegisterChanges();
                                    }
                                    catch (Exception ex)
                                    {
                                        //Feed Audit Logs
                                        Console.WriteLine(ex.Message.ToString());
                                    }
                                    break;
                                case "Stop":
                                    task.Stop();
                                    task.RegisterChanges();
                                    break;
                                case "Enable":
                                    task.Definition.Settings.Enabled = true;
                                    task.RegisterChanges();
                                    break;
                                case "Disable":
                                    task.Definition.Settings.Enabled = false;
                                    task.RegisterChanges();
                                    break;
                            }
                        }
                    }
                }
            }

            if (ListOfErrors.Count > 0)
            {
                ViewBag.ErrorList = ListOfErrors;
            }

            ViewBag.TaskStatuses = SchedulledTasksStatuses;
            ViewBag.ServerList = new SelectList(sdb.Servers.OrderBy(x => x.ServerName), "ServerName", "ServerName");
            ViewBag.SchedulledTasks = SchedulledTasks;

            return View();
        }
    }
}

MockingBird/Views/RemoteScheduleTask/Index.cshtml
@{
    ViewBag.Title = "Remote Schedule Tasks Monitoring";
    var ScheduleDetails = ViewBag.ScheduleDetails as IEnumerable<MockingBird.Models.RemoteScheduleTask>;
}

<h2>Remote Schedulle Task Monitoring</h2>

@using (Html.BeginForm())
{
    <p>
        @if (ViewBag.SchedulledTasks.Count == 0)
        {
            @Html.Raw("Select your server")
            @Html.DropDownList("ServerName", (SelectList)ViewBag.ServerList, "Please Select...", new { @class = "form-control" })

        <p>
            <input type="submit" value="Get Tasks" class="btn btn-default" />
        </p>
    }
    else
    {
        <p>
            @Html.Raw("Selected Server: " + "<b>" + ViewBag.SelectedServerName + "</b>")
        </p>
        <p>
            @Html.ActionLink("Change selected server", "Index", "RemoteScheduleTask")
        </p>

        @Html.Raw("Select your schedulled Task")

        <input type="hidden" value="@ViewBag.SelectedServerName" name="ServerName" />
        @*@Html.TextBox("ServerName", (string)ViewBag.SelectedServerName, new { @class = "hidden" })*@
        @Html.DropDownList("ScheduleTask", new SelectList(((List<string>)ViewBag.SchedulledTasks).Select(d => new SelectListItem { Text = d, Value = d }), "Value", "Text", "Please Select..."), new { @class = "form-control" })
        <br />
        <p>
            <input type="submit" value="Get Details" class="btn btn-default" />
        </p>
    }
        </p>
    }

@if (ViewBag.ScheduleDetails != null)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Schedule Task Detail</th>
                <th>Value/Result</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Schedulled Task Name</td>
                <td>@ViewBag.ScheduleDetails.SchedulledTaskName</td>
            </tr>
            <tr>
                <td>Last Task Result</td>
                <td>
                    @ViewBag.ScheduleDetails.LastTaskResult

                    @if (!string.IsNullOrEmpty(ViewBag.ScheduleDetails.LastTaskResult))
                    {
                        try
                        {
                            @Html.Raw("(")
                            @ViewBag.TaskStatuses[Convert.ToDouble(ViewBag.ScheduleDetails.LastTaskResult)]
                            @Html.Raw(")")
                        }
                        catch
                        {
                            @Html.Raw("No description for this result)")
                        }
                    }
                </td>
            </tr>
            <tr>
                <td>Last Run Time</td>
                <td>@ViewBag.ScheduleDetails.LastRunTime</td>
            </tr>
            <tr>
                <td>Next Run Time</td>
                <td>@ViewBag.ScheduleDetails.NextRunTime</td>
            </tr>
            <tr>
                <td>Credentials Being Used</td>
                <td>@ViewBag.ScheduleDetails.Credentials</td>
            </tr>
            <tr>
                <td>Author</td>
                <td>@ViewBag.ScheduleDetails.Author</td>
            </tr>
            <tr>
                <td>Enabled/Disabled</td>
                <td>@ViewBag.ScheduleDetails.Status</td>
            </tr>
        </tbody>
    </table>

    using (Html.BeginForm())
    {
        <p>
            Task Actions for <b>@ViewBag.ScheduleDetails.SchedulledTaskName</b>
        </p>

        <p>
            <input type="hidden" value="@ViewBag.SelectedServerName" name="ServerName" />
            <input type="hidden" value="@ViewBag.ScheduleDetails.SchedulledTaskName" name="ScheduleTask" />

            <input type="submit" name="TaskToDo" value="Start" class="btn btn-default" />
            <input type="submit" name="TaskToDo" value="Stop" class="btn btn-default" />
            <input type="submit" name="TaskToDo" value="Enable" class="btn btn-default" />
            <input type="submit" name="TaskToDo" value="Disable" class="btn btn-default" />
        </p>
    }
}